import type { ProductItem } from './types';

/**
 * Sample product data for demonstration and testing
 * This represents what would be parsed from AI-generated search results
 */
export const sampleProducts: ProductItem[] = [
  {
    id: 'product-1',
    partName: 'Stainless Steel Ball Joint – 1/4" NPT',
    partUrl: 'https://www.mcmaster.com/example-1',
    supplierType: 'Distributor',
    supplierFlag: '🇺🇸',
    hasSpecSheet: true,
    material: 'AISI 304 Stainless Steel',
    threadSize: '1/4" NPT',
    loadRating: {
      lb: 250,
      n: 1100
    },
    tempRange: {
      min: { f: -40, c: -40 },
      max: { f: 250, c: 121 }
    }
  },
  {
    id: 'product-2',
    partName: 'Carbon Steel Eyebolt with Swivel',
    partUrl: 'https://www.grainger.com/example-2',
    supplierType: 'EM',
    supplierFlag: '🇺🇸',
    hasSpecSheet: true,
    material: 'Carbon Steel (ASTM A36)',
    threadSize: '1/2" NPT',
    loadRating: {
      lb: 500,
      n: 2200
    },
    tempRange: {
      min: { f: -20, c: -29 },
      max: { f: 200, c: 93 }
    }
  },
  {
    id: 'product-3',
    partName: 'Heavy-Duty Ball Joint Assembly',
    partUrl: 'https://www.mscdirect.com/example-3',
    supplierType: 'Distributor',
    supplierFlag: '🇺🇸',
    hasSpecSheet: true,
    material: 'Alloy Steel (Grade 8)',
    threadSize: '3/4" NPT',
    loadRating: {
      lb: 1000,
      n: 4450
    },
    tempRange: {
      min: { f: -30, c: -34 },
      max: { f: 300, c: 149 }
    }
  },
  {
    id: 'product-4',
    partName: 'Zinc-Plated Swivel Eye Bolt',
    partUrl: 'https://www.fastenal.com/example-4',
    supplierType: 'Distributor',
    supplierFlag: '🇺🇸',
    hasSpecSheet: true,
    material: 'Zinc-Plated Steel',
    threadSize: '3/8" NPT',
    loadRating: {
      lb: 350,
      n: 1560
    },
    tempRange: {
      min: { f: -10, c: -23 },
      max: { f: 180, c: 82 }
    }
  }
];

/**
 * Sample markdown table that would be generated by AI
 * This can be used to test the table parsing functionality
 */
export const sampleMarkdownTable = `
Here are the industrial parts matching your search:

| Part Name & Supplier Type | Material | Thread Size | Load Rating | Operating Temperature |
|---|---|---|---|---|
| [Stainless Steel Ball Joint – 1/4" NPT (Distributor)](https://www.mcmaster.com/example-1) | AISI 304 Stainless Steel | 1/4" NPT | 250 lb (1100 N) | -40°F to 250°F (-40°C to 121°C) |
| [Carbon Steel Eyebolt with Swivel (EM)](https://www.grainger.com/example-2) | Carbon Steel (ASTM A36) | 1/2" NPT | 500 lb (2200 N) | -20°F to 200°F (-29°C to 93°C) |
| [Heavy-Duty Ball Joint Assembly (Distributor)](https://www.mscdirect.com/example-3) | Alloy Steel (Grade 8) | 3/4" NPT | 1000 lb (4450 N) | -30°F to 300°F (-34°C to 149°C) |
| [Zinc-Plated Swivel Eye Bolt (Distributor)](https://www.fastenal.com/example-4) | Zinc-Plated Steel | 3/8" NPT | 350 lb (1560 N) | -10°F to 180°F (-23°C to 82°C) |

All parts are available from US-based distributors and include technical datasheets.
`;
